# Generated by Django 4.2.3 on 2025-02-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sasb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="servicos",
            field=models.ManyToManyField(
                related_name="funcionarios", to="sasb.servico"
            ),
        ),
    ]
